### PR TITLE
(maint) Add MAINTAINERS file

### PR DESCRIPTION
**Pull request by MikaelSmith**
@branan @Magisus @HAIL9000 @whopper you all ok as maintainers?

I could also see adding overlap with https://github.com/puppetlabs/ruby-hocon/blob/master/MAINTAINERS /cc @cprice404 @waynr @jpinsonault

### CODE REVIEW

**Comment by Magisus** [comment]
This is good with me. I keep my eye on the Ruby repo too, though I've never done any work on it.

**Comment by whopper** [comment]
👍

**Comment by branan** [comment]
:+1: from me, too

@HAIL9000 if you have no objections to being a maintainer, please just merge this when you start your morning!

**Comment by branan** [comment]
Re: Overlap - we should probably have a sync between cpp-hocon and ruby-hocon maintainers, but I doubt there's much knowledge overlap there right now unfortunately :(

**Comment by HAIL9000** [comment]
GitHub is upset because appveyor still hasn't passed but I've got administrative privileges 😎

**Pull request merged**
