### PR TITLE
(HC-39) Implement part of resolve_substitutions

### PR DESCRIPTION
**Pull request by MikaelSmith**
Implements portions of resolve_substitutions in existing classes
(config_value, simple_config_list, and simple_config_object); with
stubs of methods needed from resolve_context and resolve_source.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
ping @whopper

**Comment by MikaelSmith** [comment]
One of my guiding principle is we should avoid pointers unless we're dealing with class hierarchies (config_value). If we want to share some implementation, pass objects by value and for expensive copies use shared_ptrs for the private members. So I'm passing resolve_source and resolve_context by value.

**Comment by MikaelSmith** [comment]
Almost done, this could be merged as-is. There are a few helper methods that still need to be implemented.

**Comment by whopper** [comment]
Woo :+1:

**Pull request merged**
