### PR TITLE
(HC-12) Partial work on ConfigParser

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
ping @Magisus

**Comment by Magisus** [comment]
Cpplint is unhappy. Once that is fixed, do we just want to merge this even though it's unfinished?

**Comment by MikaelSmith** [comment]
Yeah, merging unfinished is probably fine.

**Comment by whopper** [comment]
I think I'm going to look at this and possibly merge tomorrow.

**Pull request merged**
